/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author AJPiquero
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        super ("Help on EZ");
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Add_Func = new javax.swing.JPanel();
        ADDSP = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Call_Func = new javax.swing.JPanel();
        CALLSP = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Comment_Func = new javax.swing.JPanel();
        COMMENTSP = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        Decrement_Func = new javax.swing.JPanel();
        DECRESP = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        Divide_Func = new javax.swing.JPanel();
        DIVSP = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        Else_Func = new javax.swing.JPanel();
        ELSEFUNSP = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        Endfor_Func = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        End_Func = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        Endif_Func = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        For_Func = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        Function_Func = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        Get_Func = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        Increment_Func = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        Integer_Func = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        linebreak = new javax.swing.JPanel();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        Multiply_Func = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        Phrase_Func = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        Power_Func = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        If_Func = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        subtract = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        subtract2 = new javax.swing.JPanel();
        jTextArea20 = new javax.swing.JTextArea();
        Search = new javax.swing.JTextField();
        jScrollPane20 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        Add_Func.setLayout(null);

        ADDSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ADDSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ADDSP.setFocusTraversalPolicyProvider(true);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Add\n\n\nDefinition:\n\n\t\tAdd function calculates the sum of \n\t\tthe first value/first variable and \n\t\tthe second value/second variable and \n\t\tstore the sum to the third variable.\n\nSyntax:\n\tExample 1:\n\t\tAdd $x , $y store to $z\n\t\tthe sum of $x and $y to be stored to $z\n\t\n\tExample 2:\n\t\tAdd 3 + 4 to $z\n\t\tthe sum of 3 and 4 to be stored to $z\n");
        jTextArea1.setFocusable(false);
        jTextArea1.setRequestFocusEnabled(false);
        ADDSP.setViewportView(jTextArea1);

        Add_Func.add(ADDSP);
        ADDSP.setBounds(10, 11, 510, 570);

        jPanel3.add(Add_Func, "card2");

        CALLSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CALLSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Call\n\nDescription:\n\t\tThe EZ Programming has a calling \n\t\tfunction, CALL, to call for the function.\n\nSyntax:\n\t\tCall *functionName ");
        jTextArea2.setFocusable(false);
        jTextArea2.setMinimumSize(new java.awt.Dimension(428, 328));
        jTextArea2.setPreferredSize(new java.awt.Dimension(428, 328));
        jTextArea2.setRequestFocusEnabled(false);
        CALLSP.setViewportView(jTextArea2);

        javax.swing.GroupLayout Call_FuncLayout = new javax.swing.GroupLayout(Call_Func);
        Call_Func.setLayout(Call_FuncLayout);
        Call_FuncLayout.setHorizontalGroup(
            Call_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Call_FuncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CALLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        Call_FuncLayout.setVerticalGroup(
            Call_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Call_FuncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CALLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jPanel3.add(Call_Func, "card2");

        COMMENTSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Comment\n\n\nDefinition:\n\n\t\tComments provide clarity to the EZ\n\t\tsource code allowing others to better\n\t\tunderstand what the code was intended\n\t\tto accomplish and greatly helping in \n\t\tdebugging the code. Comments are \n\t\tespecially important in large projects\n\t\tin which many contributors are working on\n \t\tthe source code.\n\n\t\tAdding source code comments to your EZ \n \t\tsource code is a highly recommended \n\t\tpractice. In general, it is always better \n\t\tto over comment EZ source code than to \n\t\tnot add enough.\n\nSyntax:\n\n\tComment: put your comment here\n\t");
        jTextArea3.setFocusable(false);
        jTextArea3.setRequestFocusEnabled(false);
        COMMENTSP.setViewportView(jTextArea3);

        javax.swing.GroupLayout Comment_FuncLayout = new javax.swing.GroupLayout(Comment_Func);
        Comment_Func.setLayout(Comment_FuncLayout);
        Comment_FuncLayout.setHorizontalGroup(
            Comment_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Comment_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Comment_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(COMMENTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
        );
        Comment_FuncLayout.setVerticalGroup(
            Comment_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Comment_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Comment_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(COMMENTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(212, Short.MAX_VALUE)))
        );

        jPanel3.add(Comment_Func, "card2");

        DECRESP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("Decrement\n\nDescription:\n\n\t\tThe Ez Programming DECREMENT function \n\t\tsubtracts 1 to its operand\n\nSyntax:\n\t\tDecrement *variableName");
        jTextArea4.setFocusable(false);
        jTextArea4.setRequestFocusEnabled(false);
        DECRESP.setViewportView(jTextArea4);

        javax.swing.GroupLayout Decrement_FuncLayout = new javax.swing.GroupLayout(Decrement_Func);
        Decrement_Func.setLayout(Decrement_FuncLayout);
        Decrement_FuncLayout.setHorizontalGroup(
            Decrement_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Decrement_FuncLayout.createSequentialGroup()
                .addComponent(DECRESP, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 293, Short.MAX_VALUE))
        );
        Decrement_FuncLayout.setVerticalGroup(
            Decrement_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Decrement_FuncLayout.createSequentialGroup()
                .addComponent(DECRESP, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 223, Short.MAX_VALUE))
        );

        jPanel3.add(Decrement_Func, "card2");

        DIVSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        DIVSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("Divide\n\n\nDefinition:\n\n\tDivide function calculates the quotient of the first \n value/first variable and the second value/second\n variable and store the quotient to the third variable.\n\n\n\nSyntax:\n\tExample 1:\n\tDiv $a / $b to $c\n\n\tthe quotient of $a and $b to be stored \n\t\t to $c\n\t\n\tExample 2:\n\tDiv 50 / 10 to $z\n\t\n\tthe quotient of 3 and 4 to be stored \n\t\t to $z\n\t");
        jTextArea5.setFocusable(false);
        jTextArea5.setRequestFocusEnabled(false);
        DIVSP.setViewportView(jTextArea5);

        javax.swing.GroupLayout Divide_FuncLayout = new javax.swing.GroupLayout(Divide_Func);
        Divide_Func.setLayout(Divide_FuncLayout);
        Divide_FuncLayout.setHorizontalGroup(
            Divide_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Divide_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Divide_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(DIVSP, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
        );
        Divide_FuncLayout.setVerticalGroup(
            Divide_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Divide_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Divide_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(DIVSP, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(Divide_Func, "card2");

        ELSEFUNSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ELSEFUNSP.setPreferredSize(new java.awt.Dimension(492, 436));

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("Else\n\nDescription:\n\t\n\tIn the EZ Programming Language, the Else directive \n\tprovides an alternate action when used with the \n\tIf directives. The preprocessor will include the \n\tEZ source code that follows the Else statement \n\twhen the condition for the If directive \n\tevaluates to false.\n\n\nNote:\n\nThe Else directive must be closed by an Endif directive.\n\nExample: see if else.ez\n\tFunction main\n\t\tIf 1==2\n\t\t\tSay not now\n\t\tElse\n\t\t\tSay wow\n\t\tEndif\n\tEndFunc\n\t");
        jTextArea6.setFocusable(false);
        jTextArea6.setMaximumSize(new java.awt.Dimension(492, 436));
        jTextArea6.setMinimumSize(new java.awt.Dimension(492, 436));
        jTextArea6.setPreferredSize(new java.awt.Dimension(492, 436));
        jTextArea6.setRequestFocusEnabled(false);
        ELSEFUNSP.setViewportView(jTextArea6);

        javax.swing.GroupLayout Else_FuncLayout = new javax.swing.GroupLayout(Else_Func);
        Else_Func.setLayout(Else_FuncLayout);
        Else_FuncLayout.setHorizontalGroup(
            Else_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Else_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Else_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ELSEFUNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
        );
        Else_FuncLayout.setVerticalGroup(
            Else_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Else_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Else_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ELSEFUNSP, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(Else_Func, "card2");

        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea7.setEditable(false);
        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setText("Endfor\n\nDescription:\n\n\t\tThe EZ Programming command that appear \n\t\tin the FOR loop execute until ENDFOR or \n\t\tnext value is reached. The value in the \n\t\tcounter VarName increments or \n\t\tdecrements. It is used to end a loop.\n\nSyntax:\n\t\tFor\n\t\t//code\n\t\t//code\n\t\t//code\n\t\tEndFor");
        jTextArea7.setFocusable(false);
        jTextArea7.setRequestFocusEnabled(false);
        jScrollPane7.setViewportView(jTextArea7);
        jTextArea7.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout Endfor_FuncLayout = new javax.swing.GroupLayout(Endfor_Func);
        Endfor_Func.setLayout(Endfor_FuncLayout);
        Endfor_FuncLayout.setHorizontalGroup(
            Endfor_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Endfor_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Endfor_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        Endfor_FuncLayout.setVerticalGroup(
            Endfor_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Endfor_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Endfor_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(Endfor_Func, "card2");

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea8.setEditable(false);
        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jTextArea8.setText("EndFunct\n\nDescription:\n\n\t\tA function is a group of statements \n\t\tthat together perform a task. In EZ\n\t\tProgramming must have at least one \n\t\tfunction, which is main(). It is used\n\t\tto end a function.\n\nSyntax:\n\t\tFunction *functionName\n\t\t//code\n\t\t//code\n\t\t//code\n\t\tEndFunct");
        jTextArea8.setFocusable(false);
        jTextArea8.setRequestFocusEnabled(false);
        jScrollPane8.setViewportView(jTextArea8);

        javax.swing.GroupLayout End_FuncLayout = new javax.swing.GroupLayout(End_Func);
        End_Func.setLayout(End_FuncLayout);
        End_FuncLayout.setHorizontalGroup(
            End_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(End_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(End_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        End_FuncLayout.setVerticalGroup(
            End_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(End_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(End_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(End_Func, "card2");

        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea9.setEditable(false);
        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jTextArea9.setText("Endif\n\n\nDescription\n\n\tIn the EZ Programming Language, the #endif directive closes \n\toff the directive If. When the Endif directive is encountered,\n\tpreprocessing of the opening directive is completed.\n\n\nExample: see if else.ez\n\tFunction main\n\t\tIf 1==2\n\t\t\tSay not now\n\t\tElse\n\t\t\tSay wow\n\t\tEndif\n\tEndFunc");
        jTextArea9.setFocusable(false);
        jTextArea9.setRequestFocusEnabled(false);
        jScrollPane9.setViewportView(jTextArea9);

        javax.swing.GroupLayout Endif_FuncLayout = new javax.swing.GroupLayout(Endif_Func);
        Endif_Func.setLayout(Endif_FuncLayout);
        Endif_FuncLayout.setHorizontalGroup(
            Endif_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Endif_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Endif_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        Endif_FuncLayout.setVerticalGroup(
            Endif_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Endif_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Endif_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(Endif_Func, "card2");

        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea10.setEditable(false);
        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);
        jTextArea10.setText("For\n\nDescription:\n\n\t\tIn EZ Programming built-in function, \n\t\tFOR , is a loop repetition control \n\t\tstructure that allows you to \n\t\tefficiently write a loop that needs \n\t\tto execute a specific number of times.\n\nSyntax:\n\t\tFor\n\t\t//code\n\t\t//code\n\t\t//code\n\t\tEndFor");
        jTextArea10.setFocusable(false);
        jTextArea10.setRequestFocusEnabled(false);
        jScrollPane10.setViewportView(jTextArea10);

        javax.swing.GroupLayout For_FuncLayout = new javax.swing.GroupLayout(For_Func);
        For_Func.setLayout(For_FuncLayout);
        For_FuncLayout.setHorizontalGroup(
            For_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(For_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(For_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        For_FuncLayout.setVerticalGroup(
            For_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(For_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(For_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(For_Func, "card2");

        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea11.setEditable(false);
        jTextArea11.setColumns(20);
        jTextArea11.setRows(5);
        jTextArea11.setText("Function\n\nDescription:\n\t\n\t\tA function is a group of statements \n\t\tthat together perform a task. In EZ\n\t\tProgramming must have at least one \n\t\tfunction, which is main(), and all \n\t\tthe most trivial programs can define \n\t\tadditional functions.\n\nSyntax:\n\t\tFunction *functionName\n\t\t//code\n\t\t//code\n\t\t//code\n\t\tEndFunc\n\t\t");
        jTextArea11.setFocusable(false);
        jTextArea11.setRequestFocusEnabled(false);
        jScrollPane11.setViewportView(jTextArea11);

        javax.swing.GroupLayout Function_FuncLayout = new javax.swing.GroupLayout(Function_Func);
        Function_Func.setLayout(Function_FuncLayout);
        Function_FuncLayout.setHorizontalGroup(
            Function_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Function_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Function_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        Function_FuncLayout.setVerticalGroup(
            Function_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Function_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Function_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(Function_Func, "card2");

        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea12.setEditable(false);
        jTextArea12.setColumns(20);
        jTextArea12.setRows(5);
        jTextArea12.setText("Get\n\nDescription:\n\n\t\tIn EZ Programming, Get function, it means\n\t\tto get some data into a program. An input \n\t\tcan be given from the command line. EZ\n\t\tProgramming provide a built-in function \n\t\tto read the given input and feed it to \n\t\tthe program as per requirement.\n\nSyntax:\n\t\tGet *variableName = *value ");
        jTextArea12.setFocusable(false);
        jTextArea12.setRequestFocusEnabled(false);
        jScrollPane12.setViewportView(jTextArea12);

        javax.swing.GroupLayout Get_FuncLayout = new javax.swing.GroupLayout(Get_Func);
        Get_Func.setLayout(Get_FuncLayout);
        Get_FuncLayout.setHorizontalGroup(
            Get_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Get_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Get_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        Get_FuncLayout.setVerticalGroup(
            Get_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Get_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Get_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(Get_Func, "card2");

        jScrollPane14.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea14.setEditable(false);
        jTextArea14.setColumns(20);
        jTextArea14.setRows(5);
        jTextArea14.setText("Increment\n\nDescription:\n\n\t\tThe EZ Programming INCREMENT \n\t\tfunction adds 1 to its operand. \n\nSyntax:\n\t\tINCREMENT *variableName");
        jTextArea14.setFocusable(false);
        jTextArea14.setRequestFocusEnabled(false);
        jScrollPane14.setViewportView(jTextArea14);

        javax.swing.GroupLayout Increment_FuncLayout = new javax.swing.GroupLayout(Increment_Func);
        Increment_Func.setLayout(Increment_FuncLayout);
        Increment_FuncLayout.setHorizontalGroup(
            Increment_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Increment_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Increment_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        Increment_FuncLayout.setVerticalGroup(
            Increment_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Increment_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Increment_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(Increment_Func, "card2");

        jScrollPane15.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea15.setEditable(false);
        jTextArea15.setColumns(20);
        jTextArea15.setRows(5);
        jTextArea15.setText("Integer\n\nDescription:\n\t\tUsed to define variable data types\n\nSyntax:\n\t\tInteger *variableName = *value");
        jTextArea15.setFocusable(false);
        jTextArea15.setRequestFocusEnabled(false);
        jScrollPane15.setViewportView(jTextArea15);

        javax.swing.GroupLayout Integer_FuncLayout = new javax.swing.GroupLayout(Integer_Func);
        Integer_Func.setLayout(Integer_FuncLayout);
        Integer_FuncLayout.setHorizontalGroup(
            Integer_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Integer_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Integer_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        Integer_FuncLayout.setVerticalGroup(
            Integer_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Integer_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Integer_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(Integer_Func, "card2");

        jScrollPane22.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea21.setEditable(false);
        jTextArea21.setColumns(20);
        jTextArea21.setRows(5);
        jTextArea21.setText("LineBreak\n\nDescription:\n\n\t\tUsed to print in the next line.\n");
        jTextArea21.setFocusable(false);
        jTextArea21.setRequestFocusEnabled(false);
        jScrollPane22.setViewportView(jTextArea21);

        javax.swing.GroupLayout linebreakLayout = new javax.swing.GroupLayout(linebreak);
        linebreak.setLayout(linebreakLayout);
        linebreakLayout.setHorizontalGroup(
            linebreakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(linebreakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(linebreakLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        linebreakLayout.setVerticalGroup(
            linebreakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(linebreakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(linebreakLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(linebreak, "card2");

        jScrollPane16.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea16.setEditable(false);
        jTextArea16.setColumns(20);
        jTextArea16.setRows(5);
        jTextArea16.setText("Multiply\n\n\nDefinition:\n\n\tMultiply function calculates the product of the first \n value/first variable and the second value/second\n variable and store the product to the third variable.\n\n\n\nSyntax:\n\tExample 1:\n\tMul $a * $b to $c\n\n\tthe product of $a and $b to be stored \n\t\t to $c\n\t\n\tExample 2:\n\tMul 3 * 4 to $z\n\t\n\tthe product of 3 and 4 to be stored \n\t\t to $z\n\t");
        jTextArea16.setFocusable(false);
        jTextArea16.setRequestFocusEnabled(false);
        jScrollPane16.setViewportView(jTextArea16);

        javax.swing.GroupLayout Multiply_FuncLayout = new javax.swing.GroupLayout(Multiply_Func);
        Multiply_Func.setLayout(Multiply_FuncLayout);
        Multiply_FuncLayout.setHorizontalGroup(
            Multiply_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Multiply_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Multiply_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        Multiply_FuncLayout.setVerticalGroup(
            Multiply_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Multiply_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Multiply_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(Multiply_Func, "card2");

        jScrollPane17.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea17.setEditable(false);
        jTextArea17.setColumns(20);
        jTextArea17.setRows(5);
        jTextArea17.setText("Phrase\n\nDescription:\n\n\t\tThe EZ Programming, Phrase, is a data type \n\t\tused to define a one-dimensional array\n\t\tof characters.\n\nSyntax: \n\t\tPhrase *variableName ");
        jTextArea17.setFocusable(false);
        jTextArea17.setRequestFocusEnabled(false);
        jScrollPane17.setViewportView(jTextArea17);

        javax.swing.GroupLayout Phrase_FuncLayout = new javax.swing.GroupLayout(Phrase_Func);
        Phrase_Func.setLayout(Phrase_FuncLayout);
        Phrase_FuncLayout.setHorizontalGroup(
            Phrase_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Phrase_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Phrase_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        Phrase_FuncLayout.setVerticalGroup(
            Phrase_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Phrase_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Phrase_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(Phrase_Func, "card2");

        jScrollPane18.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea18.setEditable(false);
        jTextArea18.setColumns(20);
        jTextArea18.setRows(5);
        jTextArea18.setText("Power\n\nDescription:\n\n\tThe Power function returns x raised to the \n\tpower of y.");
        jTextArea18.setFocusable(false);
        jTextArea18.setRequestFocusEnabled(false);
        jScrollPane18.setViewportView(jTextArea18);

        javax.swing.GroupLayout Power_FuncLayout = new javax.swing.GroupLayout(Power_Func);
        Power_Func.setLayout(Power_FuncLayout);
        Power_FuncLayout.setHorizontalGroup(
            Power_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(Power_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Power_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        Power_FuncLayout.setVerticalGroup(
            Power_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(Power_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Power_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.add(Power_Func, "card2");

        jScrollPane19.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea19.setEditable(false);
        jTextArea19.setColumns(20);
        jTextArea19.setRows(5);
        jTextArea19.setText("Say\n\nDescription:\n\t\tThe EZ Programming built-in function, SAY,\n\t\tused to output data in the screen.");
        jTextArea19.setFocusable(false);
        jTextArea19.setRequestFocusEnabled(false);
        jScrollPane19.setViewportView(jTextArea19);

        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea13.setEditable(false);
        jTextArea13.setColumns(20);
        jTextArea13.setRows(5);
        jTextArea13.setText("If\n\nDescription:\n\n\tIn the EZ Programming , the If directive allows \n for conditional compilation. The preprocessor evaluates\n an expression provided with the If directive to \n determine if the subsequent code should be included \n in the compilation process.\n\n\nSystax:\t\n\n\tIf conditonal_expression\n\t\n\t\nconditional_expression\n\t- Expression that the preprocessor will \n \tevaluate to determine if the EZ source code\n\tthat follows the If directive will be included\n\tinto the final compiled application.\n\nExample:\n\t\n\tIf x==0\n\t\n\tor\n\t\n\tIf $a==$c");
        jTextArea13.setFocusable(false);
        jTextArea13.setRequestFocusEnabled(false);
        jScrollPane13.setViewportView(jTextArea13);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout If_FuncLayout = new javax.swing.GroupLayout(If_Func);
        If_Func.setLayout(If_FuncLayout);
        If_FuncLayout.setHorizontalGroup(
            If_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(If_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(If_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(If_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(If_FuncLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        If_FuncLayout.setVerticalGroup(
            If_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(If_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(If_FuncLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(If_FuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(If_FuncLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(If_Func, "card2");

        jScrollPane21.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane21.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextArea20.setEditable(false);
        jTextArea20.setColumns(20);
        jTextArea20.setRows(5);
        jTextArea20.setText("Subtract\n\nDefinition:\n\n\t\tSubtract function calculates the \n\t\tdifference of the first value/first\n\t\tvariable and the second value/second\n \t\tvariable and store the difference to \n\t\tthird variable.\n\n\n\nSyntax:\n\tExample 1:\n\tSub $a - $b to $c\n\n\tthe difference of $a and $b to be stored \n\t\t to $c\n\t\n\tExample 2:\n\tSub 50 - 10 to $z\n\t\n\tthe difference of 50 and 10 to be stored \n\t\t to $z\n\t");
        jTextArea20.setFocusable(false);
        jTextArea20.setRequestFocusEnabled(false);

        javax.swing.GroupLayout subtract2Layout = new javax.swing.GroupLayout(subtract2);
        subtract2.setLayout(subtract2Layout);
        subtract2Layout.setHorizontalGroup(
            subtract2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
            .addGroup(subtract2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(subtract2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextArea20, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        subtract2Layout.setVerticalGroup(
            subtract2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(subtract2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(subtract2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextArea20, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jScrollPane21.setViewportView(subtract2);

        javax.swing.GroupLayout subtractLayout = new javax.swing.GroupLayout(subtract);
        subtract.setLayout(subtractLayout);
        subtractLayout.setHorizontalGroup(
            subtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subtractLayout.createSequentialGroup()
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 293, Short.MAX_VALUE))
        );
        subtractLayout.setVerticalGroup(
            subtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subtractLayout.createSequentialGroup()
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 223, Short.MAX_VALUE))
        );

        jPanel3.add(subtract, "card2");

        jPanel1.add(jPanel3);
        jPanel3.setBounds(194, 11, 785, 745);

        Search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Search.setText("Search");
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchKeyPressed(evt);
            }
        });
        jPanel1.add(Search);
        Search.setBounds(20, 20, 140, 30);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton1.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton2.setText("Call");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton2.setOpaque(false);
        jButton2.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton3.setText("Comment");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton3.setOpaque(false);
        jButton3.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton4.setText("Decrement");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton4.setOpaque(false);
        jButton4.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 255, 153));
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton5.setText("Divide");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton5.setOpaque(false);
        jButton5.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 255, 153));
        jButton6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton6.setText("Else");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton6.setOpaque(false);
        jButton6.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 255, 153));
        jButton7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton7.setText("Endfor");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton7.setOpaque(false);
        jButton7.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(153, 255, 153));
        jButton8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton8.setText("EndFunct");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton8.setOpaque(false);
        jButton8.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(153, 255, 153));
        jButton9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton9.setText("Endif");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton9.setOpaque(false);
        jButton9.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(153, 255, 153));
        jButton10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton10.setText("For");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton10.setOpaque(false);
        jButton10.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(153, 255, 153));
        jButton11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton11.setText("Function");
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton11.setOpaque(false);
        jButton11.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(153, 255, 153));
        jButton12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton12.setText("Get");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton12.setOpaque(false);
        jButton12.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(153, 255, 153));
        jButton13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton13.setText("If");
        jButton13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton13.setOpaque(false);
        jButton13.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(153, 255, 153));
        jButton14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton14.setText("Increment");
        jButton14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton14.setOpaque(false);
        jButton14.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(153, 255, 153));
        jButton15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton15.setText("Integer");
        jButton15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton15.setOpaque(false);
        jButton15.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(153, 255, 153));
        jButton22.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton22.setText("LineBreak");
        jButton22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton22.setOpaque(false);
        jButton22.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(153, 255, 153));
        jButton16.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton16.setText("Multiply");
        jButton16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton16.setOpaque(false);
        jButton16.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(153, 255, 153));
        jButton17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton17.setText("Phrase");
        jButton17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton17.setOpaque(false);
        jButton17.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(153, 255, 153));
        jButton18.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton18.setText("Power");
        jButton18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton18.setOpaque(false);
        jButton18.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(153, 255, 153));
        jButton19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton19.setText("Say");
        jButton19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton19.setOpaque(false);
        jButton19.setPreferredSize(new java.awt.Dimension(30, 40));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(153, 255, 153));
        jButton21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton21.setText("Subtract");
        jButton21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton21.setOpaque(false);
        jButton21.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane20.setViewportView(jPanel2);

        jPanel1.add(jScrollPane20);
        jScrollPane20.setBounds(15, 59, 170, 474);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyPressed
        // TODO add your handling code here:
        String gettext= Search.getText().toLowerCase();
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            
            if (gettext.matches(".*add.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Add_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*call.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Call_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*comment.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Comment_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*decrement.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Decrement_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*divide.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Divide_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*else.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Else_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*endfor.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Endfor_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*endfunc.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(End_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*endif.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Endif_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*for.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(For_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*function.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Function_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*get.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Get_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*if.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(jPanel16);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*increment.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Increment_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*integer.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Integer_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*multiply.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Multiply_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*phrase.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Phrase_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*power.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(Power_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*say.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(If_Func);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            if (gettext.matches(".*sub.*"))
            {
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();

                jPanel3.add(subtract);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
            
        }    
            
    }//GEN-LAST:event_SearchKeyPressed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(If_Func);
        jPanel3.repaint();
        jPanel3.revalidate();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Power_Func);
        jPanel3.repaint();
        jPanel3.revalidate();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Phrase_Func);
        jPanel3.repaint();
        jPanel3.revalidate();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Multiply_Func);
        jPanel3.repaint();
        jPanel3.revalidate();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Integer_Func);
        jPanel3.repaint();
        jPanel3.revalidate();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Increment_Func);
        jPanel3.repaint();
        jPanel3.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPanel16);
        jPanel3.repaint();
        jPanel3.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Get_Func);
        jPanel3.repaint();
        jPanel3.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Function_Func);
        jPanel3.repaint();
        jPanel3.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(For_Func);
        jPanel3.repaint();
        jPanel3.revalidate();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Endif_Func);
        jPanel3.repaint();
        jPanel3.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(End_Func);
        jPanel3.repaint();
        jPanel3.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Endfor_Func);
        jPanel3.repaint();
        jPanel3.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Else_Func);
        jPanel3.repaint();
        jPanel3.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Divide_Func);
        jPanel3.repaint();
        jPanel3.revalidate();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Decrement_Func);
        jPanel3.repaint();
        jPanel3.revalidate();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Comment_Func);
        jPanel3.repaint();
        jPanel3.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Call_Func);
        jPanel3.repaint();
        jPanel3.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Add_Func);
        jPanel3.repaint();
        jPanel3.revalidate();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        // TODO add your handling code here:
        Search.setText("");
    }//GEN-LAST:event_SearchMouseClicked

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
    jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(subtract);
        jPanel3.repaint();
        jPanel3.revalidate();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(linebreak);
        jPanel3.repaint();
        jPanel3.revalidate();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed
public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("6.png")));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ADDSP;
    private javax.swing.JPanel Add_Func;
    private javax.swing.JScrollPane CALLSP;
    private javax.swing.JScrollPane COMMENTSP;
    private javax.swing.JPanel Call_Func;
    private javax.swing.JPanel Comment_Func;
    private javax.swing.JScrollPane DECRESP;
    private javax.swing.JScrollPane DIVSP;
    private javax.swing.JPanel Decrement_Func;
    private javax.swing.JPanel Divide_Func;
    private javax.swing.JScrollPane ELSEFUNSP;
    private javax.swing.JPanel Else_Func;
    private javax.swing.JPanel End_Func;
    private javax.swing.JPanel Endfor_Func;
    private javax.swing.JPanel Endif_Func;
    private javax.swing.JPanel For_Func;
    private javax.swing.JPanel Function_Func;
    private javax.swing.JPanel Get_Func;
    private javax.swing.JPanel If_Func;
    private javax.swing.JPanel Increment_Func;
    private javax.swing.JPanel Integer_Func;
    private javax.swing.JPanel Multiply_Func;
    private javax.swing.JPanel Phrase_Func;
    private javax.swing.JPanel Power_Func;
    private javax.swing.JTextField Search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JPanel linebreak;
    private javax.swing.JPanel subtract;
    private javax.swing.JPanel subtract2;
    // End of variables declaration//GEN-END:variables
}
